#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["mcp>=1.0"]
# ///
"""CLI for python example_server MCP server.

Generated by: generate_cli.py python example_server.py
Usage:
    uv run test_cli.py --help
    uv run test_cli.py list-tools
    uv run test_cli.py <tool-name> [--arg val ...]
    uv run test_cli.py call-tool <tool-name> [key=value ...]
"""

import argparse
import asyncio
import json
import sys
from contextlib import asynccontextmanager

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

try:
    from mcp.client.streamable_http import streamablehttp_client
    _HAS_STREAMABLE = True
except ImportError:
    _HAS_STREAMABLE = False

try:
    from mcp.client.sse import sse_client
    _HAS_SSE = True
except ImportError:
    _HAS_SSE = False

# Modify this to change how the CLI connects to the MCP server.
CLIENT_SPEC = {'command': 'python', 'args': ['example_server.py']}
CLIENT_TYPE = 'stdio'  # "url" or "stdio"


@asynccontextmanager
async def _get_session():
    """Yield an initialized MCP ClientSession."""
    if CLIENT_TYPE == "url":
        if _HAS_STREAMABLE:
            async with streamablehttp_client(CLIENT_SPEC) as (r, w, _):
                async with ClientSession(r, w) as session:
                    await session.initialize()
                    yield session
        elif _HAS_SSE:
            async with sse_client(CLIENT_SPEC) as (r, w):
                async with ClientSession(r, w) as session:
                    await session.initialize()
                    yield session
        else:
            raise RuntimeError(
                "No HTTP transport available. "
                "Install mcp with: pip install 'mcp[http]'"
            )
    else:
        params = StdioServerParameters(**CLIENT_SPEC)
        async with stdio_client(params) as (r, w):
            async with ClientSession(r, w) as session:
                await session.initialize()
                yield session


async def _call_tool(name: str, arguments: dict) -> None:
    async with _get_session() as session:
        result = await session.call_tool(name, arguments)
        is_error = getattr(result, "isError", False)
        if is_error:
            for block in result.content:
                print("Error:", getattr(block, "text", repr(block)), file=sys.stderr)
            sys.exit(1)
        for block in result.content:
            text = getattr(block, "text", None)
            if text is not None:
                print(text)
            else:
                print(repr(block))


# ── Utility command handlers ──────────────────────────────────────────────────

async def _handle_list_tools(args):
    async with _get_session() as session:
        result = await session.list_tools()
        if not result.tools:
            print("No tools found.")
            return
        for tool in result.tools:
            schema = tool.inputSchema or {}
            props = schema.get("properties", {}) if isinstance(schema, dict) else {}
            req = set(schema.get("required", [])) if isinstance(schema, dict) else set()
            parts = []
            for pname, pschema in props.items():
                pt = pschema.get("type", "?")
                parts.append(f"{pname}: {pt}" if pname in req else f"[{pname}: {pt}]")
            print(f"  {tool.name}({', '.join(parts)})")
            if tool.description:
                print(f"    {tool.description}")
            print()


async def _handle_list_resources(args):
    async with _get_session() as session:
        result = await session.list_resources()
        if not result.resources:
            print("No resources found.")
            return
        for r in result.resources:
            print(f"  {r.uri}")
            if r.description:
                print(f"    {r.description}")
        print()


async def _handle_read_resource(args):
    async with _get_session() as session:
        result = await session.read_resource(args.uri)
        for block in result.contents:
            text = getattr(block, "text", None)
            if text is not None:
                print(text)
            else:
                print(repr(block))


async def _handle_list_prompts(args):
    async with _get_session() as session:
        result = await session.list_prompts()
        if not result.prompts:
            print("No prompts found.")
            return
        for p in result.prompts:
            arg_names = [a.name for a in (p.arguments or [])]
            suffix = f"({', '.join(arg_names)})" if arg_names else ""
            print(f"  {p.name}{suffix}")
            if p.description:
                print(f"    {p.description}")
        print()


async def _handle_call_tool_generic(args):
    """Generic call-tool handler: name + key=value pairs."""
    parsed: dict = {}
    for item in args.tool_args:
        if "=" not in item:
            print(f"Error: expected key=value, got {item!r}", file=sys.stderr)
            sys.exit(1)
        k, v = item.split("=", 1)
        try:
            parsed[k] = json.loads(v)
        except json.JSONDecodeError:
            parsed[k] = v
    await _call_tool(args.tool_name, parsed)


def _setup_add(sub):
    p = sub.add_parser('add', help='Add two numbers together.')
    p.add_argument('--a', dest='a', type=float, required=True, help='First operand')
    p.add_argument('--b', dest='b', type=float, required=True, help='Second operand')
    p.set_defaults(_handler=_handle_add)

async def _handle_add(args):
    arguments = {
        'a': args.a,
        'b': args.b,
    }
    arguments = {k: v for k, v in arguments.items() if v is not None}
    await _call_tool('add', arguments)
def _setup_greet(sub):
    p = sub.add_parser('greet', help='Return a personalised greeting.')
    p.add_argument('--name', dest='name', type=str, required=True, help='Name to greet')
    p.add_argument('--loud', dest='loud', action='store_true', help='Shout the greeting')
    p.add_argument('--times', dest='times', type=int, required=False, help='How many times to repeat')
    p.set_defaults(_handler=_handle_greet)

async def _handle_greet(args):
    arguments = {
        'name': args.name,
        'loud': args.loud,
        'times': args.times,
    }
    arguments = {k: v for k, v in arguments.items() if v is not None}
    await _call_tool('greet', arguments)
def _setup_join(sub):
    p = sub.add_parser('join', help='Join a list of strings with a separator.')
    p.add_argument('--words', dest='words', nargs='+', type=str, required=True, help='Words to join')
    p.add_argument('--sep', dest='sep', type=str, required=False, help='Separator (default: space)')
    p.set_defaults(_handler=_handle_join)

async def _handle_join(args):
    arguments = {
        'words': args.words,
        'sep': args.sep,
    }
    arguments = {k: v for k, v in arguments.items() if v is not None}
    await _call_tool('join', arguments)
def _setup_echo_json(sub):
    p = sub.add_parser('echo_json', help='Echo back a JSON object.')
    p.add_argument('--payload', dest='payload', type=str, required=True, help='Any JSON object (JSON string)')
    p.set_defaults(_handler=_handle_echo_json)

async def _handle_echo_json(args):
    arguments = {
        'payload': json.loads(args.payload) if isinstance(args.payload, str) else args.payload,
    }
    arguments = {k: v for k, v in arguments.items() if v is not None}
    await _call_tool('echo_json', arguments)

# ── CLI wiring ────────────────────────────────────────────────────────────────

_UTIL_HANDLERS = {
    "list-tools":      _handle_list_tools,
    "list-resources":  _handle_list_resources,
    "read-resource":   _handle_read_resource,
    "list-prompts":    _handle_list_prompts,
    "call-tool":       _handle_call_tool_generic,
}


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cli.py",
        description="CLI for python example_server MCP server",
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # Utility commands
    sub.add_parser("list-tools",      help="List available tools")
    sub.add_parser("list-resources",  help="List available resources")
    rr = sub.add_parser("read-resource", help="Read a resource by URI")
    rr.add_argument("uri", help="Resource URI")
    sub.add_parser("list-prompts",    help="List available prompts")

    ct = sub.add_parser("call-tool",  help="Call a tool by name with key=value args")
    ct.add_argument("tool_name",  help="Tool name")
    ct.add_argument("tool_args",  nargs="*", metavar="key=value", help="Tool arguments")

    # Generated per-tool subcommands
    _setup_tool_subparsers(sub)

    return parser


def _setup_tool_subparsers(sub):
    _setup_add(sub)
    _setup_greet(sub)
    _setup_join(sub)
    _setup_echo_json(sub)


def main():
    parser = _build_parser()
    args = parser.parse_args()

    handler = getattr(args, "_handler", None)
    if handler is None:
        handler = _UTIL_HANDLERS.get(args.command)
    if handler is None:
        parser.print_help()
        sys.exit(1)

    asyncio.run(handler(args))


if __name__ == "__main__":
    main()
